---
# Traefik AWS Handlers

- name: Restart traefik-aws
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_aws_base_dir }}"
    state: present
    restarted: true
  listen: Restart traefik-aws
