---
# Docker Log Forwarder handlers

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart docker-log-forwarder
  ansible.builtin.systemd:
    name: docker-log-forwarder
    state: restarted
  when: docker_log_forwarder_enabled | default(true)
